-- Teleport rooms of each city and the hunts behind every teleport.
-- Generated from the Zorva map (teleports of the rooms next to the temples,
-- the monster shown beside each one and the spawns within 150 steps of
-- where it lands). level: the recommended level the hunt tasks use.

WIKI_TELEPORTS = {
    { city = 'Avante', rooms = {
        { floor = '1 andar abaixo do térreo', teleports = 16, hunts = {
            { 'Poison Spider', 9, 'Wasp, Cave Rat, Rat', 1, { type = 36, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Bear', 9, 'Wasp, Cave Rat, Rat', 1, { type = 16, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Troll', 9, '', 1, { type = 15, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Wasp', 10, 'Cave Rat, Rat, Minotaur', 1, { type = 44, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Goblin', 10, 'Cave Rat, Rat, Demon Skeleton', 1, { type = 61, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Orc', 10, 'Dragon Hatchling, Dragon, Orc Spearman', 1, { type = 5, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Skeleton', 12, 'Goblin, Cave Rat, Rat', 1, { type = 33, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Elf', 14, 'Goblin, Cave Rat, Rat', 1, { type = 62, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Dwarf', 14, 'Dwarf Guard, Goblin, Demon Skeleton', 1, { type = 69, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Minotaur', 15, 'Wasp, Cave Rat, Rat', 1, { type = 25, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Bandit', 18, 'Wasp, Cave Rat, Rat', 1, { type = 129, head = 58, body = 59, legs = 45, feet = 114, addons = 0 } },
            { 'Tortoise', 22, 'Thornback Tortoise, Crab, Blood Crab', 1, { type = 197, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Cyclops', 30, 'Cyclops Smith, Cyclops Drone, Demon Skeleton', 1, { type = 22, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Dragon Hatchling', 34, 'Dragon, Orc Leader, Orc', 1, { type = 271, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Demon Skeleton', 40, 'Goblin, Dwarf Guard, Cave Rat', 1, { type = 37, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Necromancer', 68, 'Cyclops, Demon Skeleton, Cyclops Smith', 1, { type = 9, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
        } },
    } },
    { city = 'Ventera', rooms = {
        { floor = 'térreo', teleports = 28, hunts = {
            { 'Cyclops', 30, 'Rotworm, Carrion Worm, Dragon Lord', 1, { type = 22, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Vampire', 46, 'Rotworm, Carrion Worm, Cyclops', 1, { type = 68, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Wailing Widow', 58, 'Walkay, Glifirion, Minotaur Amazon', 1, { type = 347, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Dragon', 76, 'Rotworm, Carrion Worm, Cyclops', 1, { type = 34, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Ogre Brute', 82, 'Ogre Savage', 1, { type = 857, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Giant Spider', 88, '', 1, { type = 38, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Hero', 105, 'Rotworm, Carrion Worm, Cyclops', 1, { type = 73, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Crustacea Gigantica', 134, '', 1, { type = 383, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Lost Husher', 134, 'Rotworm, Carrion Worm, Cyclops', 1, { type = 537, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Dragon Lord', 147, 'Cyclops, Dragon Lord Hatchling, Dragon', 3, { type = 39, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Minotaur Amazon', 151, 'Walkay, Mooh\'Tah Warrior, Wailing Widow', 1, { type = 608, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Sea Serpent', 156, '', 1, { type = 275, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Draptor', 160, 'Walkay, Glifirion, Wailing Widow', 2, { type = 382, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Werelioness', 164, 'Glifirion, Ankro Fighter, Crazed Beggar', 1, { type = 1301, head = 58, body = 2, legs = 94, feet = 94, addons = 0 } },
            { 'Enslaved Dwarf', 171, 'Berol, Glifirion, White Lion', 1, { type = 494, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Berol', 190, 'Glifirion, Enslaved Dwarf, White Lion', 1, { type = 295, head = 95, body = 114, legs = 76, feet = 57, addons = 1 } },
            { 'Glifirion', 190, 'Walkay, Crazed Beggar, Vulkongra', 1, { type = 278, head = 95, body = 114, legs = 76, feet = 57, addons = 1 } },
            { 'Caribian Pirate', 197, 'Corsair', 1, { type = 151, head = 114, body = 42, legs = 97, feet = 116, addons = 3 } },
            { 'Warlock', 217, 'Ogre Rowdy, Dragon Lord', 1, { type = 130, head = 19, body = 71, legs = 128, feet = 128, addons = 1 } },
            { 'Ogre Rowdy', 223, 'Warlock, Dragon Lord', 1, { type = 1213, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Weeper', 242, 'Vulkongra, Glifirion, Larva Golem', 1, { type = 489, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Falcon Knight', 276, 'Falcon Paladin, Monk', 1, { type = 1071, head = 57, body = 75, legs = 38, feet = 86, addons = 1 } },
            { 'Cobra Assassin', 337, 'Cobra Scout, Cobra Vizier, Demon Skeleton', 1, { type = 1217, head = 2, body = 2, legs = 77, feet = 1, addons = 1 } },
            { 'Morgaroth', 480, 'Brachiodemon, Cloak Of Terror, Many Faces', 1, { type = 12, head = 0, body = 94, legs = 79, feet = 79, addons = 0 } },
            { 'Ghazbaran', 480, 'Demon', 1, { type = 12, head = 0, body = 123, legs = 97, feet = 94, addons = 0 } },
        } },
        { floor = '1 andar abaixo do térreo', teleports = 43, hunts = {
            { 'Demon Skeleton', 40, 'Dragon Lord, Banshee, Necromancer', 2, { type = 37, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Pirate Corsair', 50, 'Pirate Cutthroat, Pirate Buccaneer, Pirate Marauder', 1, { type = 98, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Mutated Rat', 58, '', 1, { type = 305, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Golden Servant', 58, 'Magma Crawler, Egipt Mummy, Lugia Scorpion', 1, { type = 396, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Pixie', 76, 'Golden Servant, Spidris, Draken Warmaster', 2, { type = 982, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Bog Raider', 82, 'Berserker Rat, Hellspawn, Amazon', 1, { type = 299, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Undead Gladiator', 82, 'Elder Beholder', 1, { type = 306, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Giant Spider', 88, '', 1, { type = 38, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Lizard Legionnaire', 100, 'Draken Warmaster, Lizard Chosen, Lizard Dragon Priest', 1, { type = 338, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Metal Gargoyle', 109, 'Infernalist, Noldor Elf, War Golem', 1, { type = 601, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Crazed Beggar', 125, 'Warmaster, Rat', 1, { type = 153, head = 59, body = 38, legs = 38, feet = 97, addons = 3 } },
            { 'Noldor Elf', 125, 'Muddy Earth Elemental, Master Hunter, Amazon', 2, { type = 64, head = 95, body = 114, legs = 76, feet = 57, addons = 1 } },
            { 'Studant', 134, 'Studant of Magic, Studantt of Magic, Harry Porco', 1, { type = 128, head = 95, body = 114, legs = 76, feet = 57, addons = 1 } },
            { 'Werewolf', 139, 'Egipt Mummy, Amazon, Ankro Moohtant', 1, { type = 308, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Dragon Lord', 147, 'Warlock, Minotaur Guard, Demon', 4, { type = 39, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Elder Lion', 164, 'Lost Berserker', 1, { type = 570, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Diabolic Imp', 179, 'Demon', 1, { type = 237, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Glifirion', 190, 'Ankro Fighter, Berol, Enslaved Dwarf', 1, { type = 278, head = 95, body = 114, legs = 76, feet = 57, addons = 1 } },
            { 'Infernalist', 217, 'Elder Lion', 1, { type = 130, head = 78, body = 76, legs = 94, feet = 115, addons = 2 } },
            { 'Skeleton Beast', 217, 'Guardian Assassin, Hero', 1, { type = 101, head = 95, body = 114, legs = 76, feet = 57, addons = 1 } },
            { 'Lost Soul', 217, 'Hellspawn, Undead Dragon, Blistering Fire Elemental', 1, { type = 232, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Ghastly Dragon', 236, 'Cliff Strider, Ghastly Wyrm, Ogre Rowdy', 1, { type = 351, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Cliff Strider', 268, 'Lost Berserker, Deepling Guard, Mav Gnome', 2, { type = 497, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Demon', 277, 'Hero, Necrolord, Monk', 5, { type = 35, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Arvore Demoniaca', 277, 'Demon', 1, { type = 310, head = 95, body = 114, legs = 76, feet = 57, addons = 1 } },
            { 'Guzzlemaw', 278, 'Frazzlemaw', 1, { type = 584, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Larva Golem', 282, 'Magma Crawler, Weeper', 1, { type = 491, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Vexclaw', 284, 'Grimeleech, Hellflayer, Hellhound', 1, { type = 854, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Resistence Guard', 309, 'Resistence Archer, Skeleton Warrior', 1, { type = 1317, head = 57, body = 21, legs = 95, feet = 95, addons = 1 } },
            { 'Necrovigi', 329, '', 1, { type = 514, head = 20, body = 114, legs = 114, feet = 29, addons = 0 } },
            { 'Blazing Human', 329, 'Pirate Skeleton, Skeleton Beast, Pirate Ghost', 1, { type = 1152, head = 95, body = 114, legs = 76, feet = 57, addons = 1 } },
            { 'Cloak Of Terror', 652, '', 1, { type = 1295, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
        } },
        { floor = '1 andar abaixo do térreo', teleports = 6, hunts = {
            { 'Hero Priest', 151, '', 1, { type = 386, head = 78, body = 94, legs = 40, feet = 40, addons = 1 } },
            { 'Blair Witch', 223, 'Spectre Witch, Dragon Hunter, Draken Abomination', 2, { type = 988, head = 95, body = 114, legs = 76, feet = 57, addons = 1 } },
            { 'Ghastly Dragon', 236, 'Lizard Chosen, Draken Warmaster, Lizard Dragon Priest', 1, { type = 351, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Dragonath', 263, '', 1, { type = 947, head = 95, body = 57, legs = 113, feet = 113, addons = 3 } },
            { 'Black Sphinx Acolyte', 309, 'Sphinx', 1, { type = 1200, head = 114, body = 95, legs = 94, feet = 95, addons = 0 } },
        } },
        { floor = 'térreo', teleports = 2, hunts = {
            { 'Rotworm', 13, 'Carrion Worm, Cyclops, Hero', 1, { type = 26, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Necrolord', 217, 'Elder Lion, Ghoul, Ghost', 1, { type = 145, head = 20, body = 114, legs = 0, feet = 114, addons = 3 } },
        } },
        { floor = 'térreo', teleports = 4, hunts = {
            { 'Kongra', 25, 'Sibang, Ape Lord, Asura', 1, { type = 116, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Haunted Treeling', 46, 'Ankro Fighter, Spectre Witch, Ankro Archer', 1, { type = 310, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Quara Predator', 125, 'Seacrest Serpent, Quara Predator Scout', 1, { type = 20, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Hellspawn', 165, 'Draken Abomination, Juggernaut', 1, { type = 322, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
        } },
    } },
    { city = 'Carlin', rooms = {
        { floor = '1 andar abaixo do térreo', teleports = 24, hunts = {
            { 'Bog Raider', 82, 'Noldor Elf, Muddy Earth Elemental, Noldor Exodio', 1, { type = 299, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Werebadger', 125, 'Berserker Rat, Hellspawn, Guardian Assassin', 1, { type = 729, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Noldor Elf', 125, 'Muddy Earth Elemental, Noldor Exodio, Master Hunter', 1, { type = 64, head = 95, body = 114, legs = 76, feet = 57, addons = 1 } },
            { 'Stone Rhino', 134, 'Berserker Rat, Corsair, Fury', 1, { type = 936, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Werewolf', 139, 'Egipt Mummy, Mummy, Amazon', 1, { type = 308, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Nightfiend', 147, 'Werebear, Bog Raider, Amazon', 1, { type = 556, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Werebear', 147, 'Nightfiend, Mutated Bat', 1, { type = 720, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Destroyer', 164, 'Hellspawn, Berserker Rat, Guardian Assassin', 1, { type = 236, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Orc Berserker', 164, 'Fury, Orc Warlord, Amazon', 1, { type = 8, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Hellspawn', 165, 'Berserker Rat, Guardian Assassin', 1, { type = 322, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Master Hunter', 188, 'Noldor Elf, Muddy Earth Elemental, Noldor Exodio', 1, { type = 129, head = 95, body = 116, legs = 121, feet = 115, addons = 3 } },
            { 'Berserker Rat', 190, 'Hellspawn, Guardian Assassin, Destroyer', 2, { type = 305, head = 95, body = 114, legs = 76, feet = 57, addons = 1 } },
            { 'Noldor Templar', 190, 'Noldor Elf', 1, { type = 63, head = 95, body = 114, legs = 76, feet = 57, addons = 1 } },
            { 'Sea Predator', 204, '', 1, { type = 413, head = 95, body = 114, legs = 76, feet = 57, addons = 1 } },
            { 'Fury', 204, 'Noldor Elf, Master Hunter, Orc Warlord', 1, { type = 149, head = 94, body = 77, legs = 96, feet = 0, addons = 3 } },
            { 'Corsair', 210, 'Stone Rhino, Berserker Rat, Clomp', 1, { type = 96, head = 95, body = 114, legs = 76, feet = 57, addons = 1 } },
            { 'Skeleton Beast', 217, '', 1, { type = 101, head = 95, body = 114, legs = 76, feet = 57, addons = 1 } },
            { 'Noldor Exodio', 233, 'Noldor Elf, Master Hunter, Amazon', 1, { type = 990, head = 95, body = 114, legs = 76, feet = 57, addons = 1 } },
            { 'Guardian Assassin', 263, 'Amazon, Bog Raider, Ankro Moohtant', 2, { type = 152, head = 114, body = 124, legs = 124, feet = 124, addons = 3 } },
            { 'Grim Reaper', 263, 'Berserker Rat, Fury, Amazon', 2, { type = 300, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Saruman Warlord', 989, 'Voidborn', 1, { type = 143, head = 77, body = 126, legs = 0, feet = 0, addons = 3 } },
        } },
    } },
    { city = 'Basco', rooms = {
        { floor = 'térreo', teleports = 16, hunts = {
            { 'Giant Spider', 88, 'Frazzlemaw', 1, { type = 38, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Noldor Elf', 125, 'Noldor Fury, Blood Necrolord, Black Crocodile', 1, { type = 64, head = 95, body = 114, legs = 76, feet = 57, addons = 1 } },
            { 'Lost Husher', 134, 'Hero Priest, Warlock, Dragon Lord', 1, { type = 537, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Hydra', 147, 'Askarak Lord, Askarak Demon', 1, { type = 121, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Dragon Lord', 147, 'Frazzlemaw, Ghastly Wyrm, Berserker Tiger', 1, { type = 39, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Hero Priest', 151, 'Warlock, Berserker Tiger, Orewalker', 1, { type = 386, head = 78, body = 94, legs = 40, feet = 40, addons = 1 } },
            { 'Jacob', 151, 'Blair Witch, Werebear, Black Crocodile', 1, { type = 731, head = 95, body = 114, legs = 76, feet = 57, addons = 1 } },
            { 'Dragonling', 151, 'Infernalist, Fire Elemental, Dragon Lord', 1, { type = 505, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Shock Head', 156, 'Black Crocodile, Noldor Elf, Necrolord', 1, { type = 579, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Sea Serpent', 156, 'Zumbi, Abobora, Resistence Guard', 1, { type = 275, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Black Crocodile', 160, 'Noldor Elf, Blood Necrolord, Jacob', 1, { type = 358, head = 95, body = 114, legs = 76, feet = 57, addons = 1 } },
            { 'Zumbi', 164, 'Sea Serpent, Resistence Guard, Abobora', 1, { type = 311, head = 95, body = 114, legs = 76, feet = 57, addons = 1 } },
            { 'Moohtant', 167, 'Hero Priest, Warlock, Berserker Tiger', 1, { type = 607, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Berserker Tiger', 190, 'Warlock, Hero Priest, Orewalker', 1, { type = 318, head = 95, body = 114, legs = 76, feet = 57, addons = 1 } },
            { 'Noldor Fury', 191, 'Noldor Elf, Necrolord, Noldor Templar', 1, { type = 569, head = 95, body = 114, legs = 76, feet = 57, addons = 1 } },
            { 'Brimstone Bug', 197, 'Zumbi, Giant Spider, Walker', 1, { type = 352, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
        } },
        { floor = '1 andar acima do térreo', teleports = 22, hunts = {
            { 'Dragon Lord', 147, 'Ghastly Wyrm', 1, { type = 39, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Brefon', 165, 'Jacob, Berserker Tiger, Warlock', 1, { type = 256, head = 95, body = 114, legs = 76, feet = 57, addons = 1 } },
            { 'Frazzlemaw', 208, 'Jacob, Dragon Lord, Black Crocodile', 1, { type = 594, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Warlock', 217, 'Hero Priest, Berserker Tiger, Orewalker', 1, { type = 130, head = 19, body = 71, legs = 128, feet = 128, addons = 1 } },
            { 'Infernalist', 217, 'Lost Husher, Lost Thrower, Dwarf Guard', 1, { type = 130, head = 78, body = 76, legs = 94, feet = 115, addons = 2 } },
            { 'Medusa', 219, 'Zumbi, Sea Serpent, Draken Elite', 1, { type = 330, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Draken Elite', 223, 'Zumbi, Hero Priest, Brimstone Bug', 1, { type = 362, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Blood Necrolord', 223, 'Noldor Elf, Noldor Fury, Black Crocodile', 1, { type = 145, head = 94, body = 94, legs = 0, feet = 115, addons = 3 } },
            { 'Blair Witch', 223, 'Jacob, Black Crocodile, Werebear', 1, { type = 988, head = 95, body = 114, legs = 76, feet = 57, addons = 1 } },
            { 'Ithirion Mage', 230, 'Imperial Witch, Darkness Priestess', 1, { type = 354, head = 95, body = 114, legs = 76, feet = 57, addons = 1 } },
            { 'Flimsy Lost Soul', 233, 'Quimera, Hydra, Manticore', 1, { type = 1268, head = 0, body = 26, legs = 0, feet = 0, addons = 1 } },
            { 'Ghastly Dragon', 236, 'Demon', 1, { type = 351, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Orewalker', 242, 'Warlock, Hero Priest, Berserker Tiger', 1, { type = 490, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Ghastly Wyrm', 254, 'Dragon Lord', 1, { type = 562, head = 95, body = 114, legs = 76, feet = 57, addons = 1 } },
            { 'Abomination', 263, 'Warlock, Hero Priest, Berserker Tiger', 1, { type = 364, head = 95, body = 114, legs = 76, feet = 57, addons = 1 } },
            { 'Grim Reaper', 263, 'Zumbi, Draken Elite, Moohtant', 1, { type = 300, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Guardian Assassin', 263, 'Blood Necrolord, Black Crocodile, Noldor Elf', 1, { type = 152, head = 114, body = 124, legs = 124, feet = 124, addons = 3 } },
            { 'Cliff Strider', 268, '', 1, { type = 497, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Demon', 277, 'Ghastly Dragon', 1, { type = 35, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Abobora', 304, 'Zumbi, Brimstone Bug, Sea Serpent', 1, { type = 292, head = 95, body = 114, legs = 76, feet = 57, addons = 1 } },
            { 'Quimera', 348, 'Flimsy Lost Soul, Hydra, Manticore', 1, { type = 1197, head = 95, body = 114, legs = 76, feet = 57, addons = 1 } },
            { 'Rage Squid', 477, 'Blair Witch', 1, { type = 1059, head = 94, body = 78, legs = 78, feet = 0, addons = 0 } },
        } },
    } },
    { city = 'Cidade Real', rooms = {
        { floor = '1 andar abaixo do térreo', teleports = 18, hunts = {
            { 'Broken Shaper', 125, 'Valorcrest, Demon, Nightmare', 1, { type = 932, head = 132, body = 95, legs = 0, feet = 121, addons = 0 } },
            { 'Shaper Matriarch', 127, 'Twisted Shaper, Broken Shaper, Demon', 1, { type = 933, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Shaburak Prince', 130, 'Askarak Demon, Shaburak Demon, Askarak Prince', 1, { type = 418, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Behemoth', 164, '', 1, { type = 55, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Elder Lion', 164, '', 1, { type = 570, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Warlock', 217, '', 1, { type = 130, head = 19, body = 71, legs = 128, feet = 128, addons = 1 } },
            { 'Necrolord', 217, 'Abomination', 1, { type = 145, head = 20, body = 114, legs = 0, feet = 114, addons = 3 } },
            { 'Blood Necrolord', 223, 'Ironblight', 1, { type = 145, head = 94, body = 94, legs = 0, feet = 115, addons = 3 } },
            { 'Lost Berserker', 230, 'Enslaved Dwarf', 1, { type = 496, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Ogre Ruffian', 248, '', 1, { type = 1212, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Spider Sorcerer', 263, '', 1, { type = 133, head = 0, body = 82, legs = 82, feet = 0, addons = 3 } },
            { 'Massive Fire Elemental', 273, 'Warlock, Beholder, Demon', 1, { type = 242, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Demon', 277, 'Hero, Monk, Necrolord', 2, { type = 35, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Demon Outcast', 282, '', 1, { type = 590, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Blazing Unicorn', 330, 'Infernalist, Massive Fire Elemental', 1, { type = 1017, head = 95, body = 114, legs = 76, feet = 57, addons = 1 } },
            { 'Ferumbras', 420, 'Massive Fire Elemental, Warlock, Beholder', 1, { type = 229, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Ink Blob', 469, 'Golden Servant', 1, { type = 1064, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
        } },
        { floor = '8 andares abaixo do térreo', teleports = 4, hunts = {
            { 'Lich', 88, 'Undead Dragon', 1, { type = 99, head = 95, body = 116, legs = 119, feet = 115, addons = 0 } },
            { 'Hellfire Fighter', 187, 'Hellhound', 1, { type = 243, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Defiler', 207, 'Plaguesmith', 1, { type = 238, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Lost Soul', 217, 'Dark Torturer, Banshee, Demon', 1, { type = 232, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
        } },
    } },
    { city = 'Torvena', rooms = {
        { floor = '1 andar acima do térreo', teleports = 14, hunts = {
            { 'Golden Servant', 58, 'Pixie, Spidris, Draken Warmaster', 1, { type = 396, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Pixie', 76, 'Moohtant, Spidris, Waspoid', 1, { type = 982, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Stampor', 81, 'Pixie, Golden Servant, Moohtant', 1, { type = 381, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Lizard Legionnaire', 100, 'Pixie, Golden Servant, Moohtant', 1, { type = 338, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Wereboar', 143, 'Pixie, Moohtant, Golden Servant', 1, { type = 721, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Deepling Guard', 147, 'Pixie, Moohtant, Waspoid', 1, { type = 442, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Draken Warmaster', 160, 'Pixie, Golden Servant, Moohtant', 1, { type = 334, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Kollos', 160, 'Pixie, Golden Servant, Spidris', 1, { type = 458, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Moohtant', 167, 'Pixie, Waspoid, Stampor', 1, { type = 607, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Spidris', 167, 'Pixie, Waspoid, Spitter', 1, { type = 457, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Tunnel Tyrant', 197, 'Pixie, Moohtant, Draken Warmaster', 1, { type = 1035, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Draken Abomination', 210, 'Draken Elite, Draken Warmaster, Lizard Legionnaire', 1, { type = 357, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Draken Elite', 223, 'Draken Abomination, Draken Warmaster, Lizard Legionnaire', 1, { type = 362, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Crazed Summer Vanguard', 248, 'Crazed Summer Rearguard, Insane Siren, Lizard High Guard', 1, { type = 1136, head = 20, body = 94, legs = 20, feet = 81, addons = 1 } },
        } },
    } },
    { city = 'Melrose', rooms = {
        { floor = '1 andar acima do térreo', teleports = 18, hunts = {
            { 'Dark Magician', 34, 'Jukay, Metal Gargoyle, Green Djinn', 1, { type = 133, head = 116, body = 95, legs = 50, feet = 132, addons = 2 } },
            { 'Green Djinn', 37, 'Jukay, Dark Magician, Metal Gargoyle', 1, { type = 51, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Crystal Wolf', 43, '', 1, { type = 391, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Metal Gargoyle', 109, '', 1, { type = 601, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Glooth Golem', 125, 'Rustheap Golem, War Golem, Worker Golem', 1, { type = 600, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Crazed Beggar', 125, 'Noldor Elf, Metal Gargoyle, Caribian Pirate', 1, { type = 153, head = 59, body = 38, legs = 38, feet = 97, addons = 3 } },
            { 'Noldor Elf', 125, 'Caribian Pirate, Ankro Fighter, Crazed Beggar', 1, { type = 64, head = 95, body = 114, legs = 76, feet = 57, addons = 1 } },
            { 'Quara Predator', 125, 'Seacrest Serpent, Quara Predator Scout', 1, { type = 20, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Ape Lord', 151, 'Metal Gargoyle, Berserker Rat, Mutated Rat', 1, { type = 738, head = 95, body = 114, legs = 76, feet = 57, addons = 1 } },
            { 'War Golem', 156, 'Rustheap Golem, Glooth Golem, Worker Golem', 1, { type = 326, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Hellspawn', 165, 'Jukay, Green Djinn, Dark Magician', 1, { type = 322, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Jukay', 167, 'Green Djinn, Hellspawn, Dark Magician', 1, { type = 665, head = 0, body = 120, legs = 120, feet = 57, addons = 2 } },
            { 'Seacrest Serpent', 167, 'Quara Predator, Quara Predator Scout', 1, { type = 675, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Berserker Rat', 190, 'Ape Lord, Mutated Rat, Giant Spider', 1, { type = 305, head = 95, body = 114, legs = 76, feet = 57, addons = 1 } },
            { 'Caribian Pirate', 197, 'Noldor Elf, Ankro Fighter, Crazed Beggar', 1, { type = 151, head = 114, body = 42, legs = 97, feet = 116, addons = 3 } },
            { 'Infernalist', 217, 'Metal Gargoyle, War Golem, Ezerus', 1, { type = 130, head = 78, body = 76, legs = 94, feet = 115, addons = 2 } },
            { 'Ithirion Mage', 230, '', 1, { type = 354, head = 95, body = 114, legs = 76, feet = 57, addons = 1 } },
            { 'Elite Assassin', 290, 'Jukay, Dark Magician, Green Djinn', 1, { type = 156, head = 20, body = 95, legs = 95, feet = 78, addons = 1 } },
        } },
    } },
    { city = 'Paw Port', rooms = {
        { floor = '1 andar acima do térreo', teleports = 8, hunts = {
            { 'Deepworm', 39, 'Cave Devourer, Diremaw', 1, { type = 1033, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Wereboar', 143, 'Chasm Spawn, Adult Goanna, Young Goanna', 3, { type = 721, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Chasm Spawn', 200, 'Wereboar, Adult Goanna, Young Goanna', 1, { type = 1037, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Young Goanna', 280, 'Wereboar, Adult Goanna', 1, { type = 1196, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'True Midnight Asura', 312, 'Asura', 1, { type = 1068, head = 72, body = 95, legs = 72, feet = 0, addons = 0 } },
            { 'Blazing Human', 329, 'Pirate Skeleton, Skeleton Beast, Pirate Ghost', 1, { type = 1152, head = 95, body = 114, legs = 76, feet = 57, addons = 1 } },
        } },
        { floor = 'térreo', teleports = 10, hunts = {
            { 'Kongra', 25, 'Sibang, Ape Lord, Asura', 1, { type = 116, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Lizard Templar', 30, 'Hydra, Kongra, Dragon Lord', 1, { type = 113, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Nymph', 85, 'Lizard Chosen, Lizard Templar, Serpent Spawn', 1, { type = 989, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Hydra', 147, 'Lizard Templar, Lizard Chosen, Serpent Spawn', 1, { type = 121, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Dragon Lord', 147, 'Kongra, Sibang, Hydra', 1, { type = 39, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Serpent Spawn', 184, 'Hydra, Lizard Chosen, Lizard Templar', 1, { type = 220, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Shaman Princess', 190, 'Kongra, Sibang, Hydra', 1, { type = 138, head = 114, body = 0, legs = 0, feet = 0, addons = 3 } },
            { 'Medusa', 219, 'Kongra, Sibang, Merlkin', 1, { type = 330, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Asura', 220, 'Kongra, Sibang, Ape Lord', 1, { type = 150, head = 0, body = 114, legs = 90, feet = 90, addons = 1 } },
            { 'Lost Berserker', 230, 'Hydra, Dragon Lord, Lizard Templar', 1, { type = 496, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
        } },
    } },
    { city = 'Namrah', rooms = {
        { floor = '1 andar abaixo do térreo', teleports = 23, hunts = {
            { 'Ankro Fighter', 115, 'Ankro Guard, Ankro Archer, Sphinx', 1, { type = 25, head = 95, body = 114, legs = 76, feet = 57, addons = 1 } },
            { 'Crazed Beggar', 125, 'Glifirion, Dragon Lord, Warmaster', 1, { type = 153, head = 59, body = 38, legs = 38, feet = 97, addons = 3 } },
            { 'Dragon Lord', 147, 'Ghastly Dragon, Dragon Lord Hatchling, Crazed Beggar', 3, { type = 39, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Sandstone Scorpion', 151, 'Crypt Warden, Dark Magician, Undead Cavebear', 1, { type = 398, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Sea Serpent', 156, '', 1, { type = 275, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Elder Wyrm', 164, 'Crazed Beggar, Dragon Lord, Wyrm', 1, { type = 561, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Elder Lion', 164, 'Necrolord, Ghoul, Ghost', 1, { type = 570, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Undead Cavebear', 164, 'Crypt Warden, Master Nomad, Sphinx', 1, { type = 384, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Dark Tortoise', 182, '', 1, { type = 303, head = 95, body = 114, legs = 76, feet = 57, addons = 1 } },
            { 'Master Nomad', 197, 'Crazed Beggar, Guardian Lady', 1, { type = 146, head = 114, body = 20, legs = 22, feet = 2, addons = 3 } },
            { 'Valorcrest', 217, 'Ankro Fighter, Warmaster, Sphinx', 1, { type = 555, head = 95, body = 114, legs = 76, feet = 57, addons = 1 } },
            { 'Necrolord', 217, 'Demon Skeleton, Ghoul, Ghost', 1, { type = 145, head = 20, body = 114, legs = 0, feet = 114, addons = 3 } },
            { 'Egipt Mummy', 223, 'Warmaster, Valorcrest, Ghastly Dragon', 1, { type = 544, head = 95, body = 114, legs = 76, feet = 57, addons = 1 } },
            { 'Ghosty', 234, 'Ghastly Dragon', 1, { type = 568, head = 95, body = 114, legs = 76, feet = 57, addons = 1 } },
            { 'Ghastly Dragon', 236, 'Dragon Lord, Dragon Lord Hatchling, Ankro Fighter', 2, { type = 351, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Priestess of the Wild Sun', 288, 'Sandstone Scorpion, Dragon Lord, Black Sphinx Acolyte', 1, { type = 1199, head = 114, body = 78, legs = 94, feet = 0, addons = 0 } },
            { 'Sphinx', 317, 'Ankro Fighter, Valorcrest, Ankro Archer', 1, { type = 1188, head = 50, body = 39, legs = 0, feet = 3, addons = 1 } },
            { 'Guardian Lady', 334, 'Ankro Fighter, Crazed Beggar, Ankro Guard', 1, { type = 150, head = 78, body = 114, legs = 114, feet = 0, addons = 3 } },
            { 'Crypt Warden', 339, 'Priestess of the Wild Sun, Undead Cavebear, Sandstone Scorpion', 1, { type = 1190, head = 41, body = 38, legs = 0, feet = 0, addons = 0 } },
            { 'Lugia', 420, '', 1, { type = 955, head = 39, body = 79, legs = 79, feet = 79, addons = 3 } },
        } },
    } },
    { city = 'Storvik', rooms = {
        { floor = 'térreo', teleports = 6, hunts = {
            { 'Mammoth', 134, 'Frost Dragon, Night Watch Guard, War Wolf', 1, { type = 199, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Frost Dragon', 147, 'Frost Dragon Hatchling', 1, { type = 248, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Ursagrodon', 164, 'Mytical', 1, { type = 548, head = 95, body = 114, legs = 76, feet = 57, addons = 1 } },
            { 'Mytical', 200, 'Ursagrodon', 1, { type = 138, head = 114, body = 124, legs = 124, feet = 124, addons = 3 } },
            { 'Crazed Winter Vanguard', 260, 'Night Watch Guard, Crazed Winter Rearguard, Frost Dragon', 1, { type = 1136, head = 0, body = 123, legs = 28, feet = 20, addons = 1 } },
            { 'Artic Unicorn', 330, '', 1, { type = 1018, head = 95, body = 114, legs = 76, feet = 57, addons = 1 } },
        } },
    } },
    { city = 'Astier', rooms = {
        { floor = 'térreo', teleports = 11, hunts = {
            { 'Gazer Spectre', 223, 'Ripper Spectre, Arachnophobica, Burster Spectre', 1, { type = 1122, head = 94, body = 20, legs = 77, feet = 20, addons = 0 } },
            { 'Feversleep', 230, 'Retching Horror, Shiversleep, Demon Outcast', 1, { type = 593, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Flimsy Lost Soul', 233, 'Mean Lost Soul, Freakish Lost Soul', 2, { type = 1268, head = 0, body = 26, legs = 0, feet = 0, addons = 1 } },
            { 'Guzzlemaw', 278, 'Frazzlemaw', 1, { type = 584, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Black Sphinx Acolyte', 309, 'Arachnophobica, Biting Book, Mossmasher', 1, { type = 1200, head = 114, body = 95, legs = 94, feet = 95, addons = 0 } },
            { 'Grey Dragon', 341, 'Dragonling, Mossmasher, Silencer', 1, { type = 927, head = 95, body = 57, legs = 113, feet = 113, addons = 3 } },
            { 'Biting Book', 361, 'Knowledge Elemental', 1, { type = 1066, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Squid Warden', 486, 'Icecold Book, Animated Feather', 1, { type = 1059, head = 9, body = 21, legs = 41, feet = 85, addons = 0 } },
            { 'Mossmasher', 604, 'Dragonling, Grey Dragon, Silencer', 1, { type = 1364, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Many Faces', 707, 'Mirror Image', 1, { type = 1296, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
        } },
    } },
    { city = 'Pinegarden', rooms = {
        { floor = 'térreo', teleports = 5, hunts = {
            { 'Weretiger', 214, 'Boar Man', 1, { type = 1646, head = 97, body = 114, legs = 113, feet = 94, addons = 1 } },
            { 'Boar Man', 322, 'Weretiger', 1, { type = 1603, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Quara Plunderer', 394, '', 1, { type = 1758, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Rootthing Amber Shaper', 428, 'Nighthunter', 1, { type = 1762, head = 0, body = 0, legs = 0, feet = 0, addons = 0 } },
            { 'Nighthunter', 433, 'Rootthing Amber Shaper', 1, { type = 1552, head = 85, body = 1, legs = 85, feet = 105, addons = 3 } },
        } },
    } },
}
